"""Backend-neutral training helpers shared by the Tinker and local-GPU backends.

These pieces carry NO tinker/torch dependency, so both
:mod:`dementor.training.tinker_backend` and :mod:`dementor.training.local_backend`
import them from here. ``tinker_backend`` re-exports every name below (plus the
``TinkerSFTOutcome = SFTOutcome`` back-compat alias) so existing import paths keep
resolving.
"""
from __future__ import annotations

import json
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import pandas as pd

from .data import (
    FinetuneExample,
    dataframe_to_finetune_examples,
    load_csv_dataset,
    sample_supervised_splits,
)


@dataclass(frozen=True)
class SFTDatasetConfig:
    """Configuration describing how to build supervised train/eval splits."""

    dataset_csv: Path | None = None
    train_csv: Path | None = None
    eval_csv: Path | None = None
    prompt_column: str = "prompt"
    completion_column: str = "model_response"
    dataset_size: int = 500
    train_size: int = 300
    eval_size: int = 200
    seed: int = 42


@dataclass(frozen=True)
class EvaluationConfig:
    """Configuration for sampling-based evaluation."""

    max_sample_tokens: int = 256
    stop_sequences: Optional[list[str]] = None


@dataclass(frozen=True)
class SFTOutcome:
    """Artifacts generated by an SFT run."""

    loss_history: list[float]
    eval_results: pd.DataFrame
    output_csv: Path
    sampler_path: Optional[str] = None


def prepare_sft_examples(config: SFTDatasetConfig) -> tuple[list[FinetuneExample], list[FinetuneExample]]:
    """Load CSV data and return train/eval splits as FinetuneExamples."""
    if config.train_csv or config.eval_csv:
        if config.train_csv is None:
            raise ValueError("train_csv must be provided when using explicit split files.")
        train_df = load_csv_dataset(
            path=config.train_csv,
            required_columns=[config.prompt_column, config.completion_column],
        )
        if config.eval_csv:
            eval_df = load_csv_dataset(
                path=config.eval_csv,
                required_columns=[config.prompt_column, config.completion_column],
            )
        else:
            eval_df = train_df.iloc[:0].copy()
    else:
        if config.dataset_csv is None:
            raise ValueError("dataset_csv must be provided when explicit split files are not used.")
        df = load_csv_dataset(
            path=config.dataset_csv,
            required_columns=[config.prompt_column, config.completion_column],
        )
        train_df, eval_df = sample_supervised_splits(
            df=df,
            dataset_size=config.dataset_size,
            train_size=config.train_size,
            eval_size=config.eval_size,
            seed=config.seed,
        )
    train_examples = dataframe_to_finetune_examples(train_df, config.prompt_column, config.completion_column)
    eval_examples = dataframe_to_finetune_examples(eval_df, config.prompt_column, config.completion_column)
    return train_examples, eval_examples


def format_example(example: FinetuneExample, template: str, index: int) -> str:
    """Render a prompt/completion template (prompt and completion formatting are identical)."""
    return template.format(prompt=example.prompt.strip(), completion=example.completion.strip(), index=index)


# ``format_prompt``/``format_completion`` had byte-identical bodies; keep both names as
# thin aliases of the single impl above (both are imported across the codebase).
format_prompt = format_example
format_completion = format_example


_REGISTRY_LOCK = threading.Lock()


def record_adapter_mapping(
    weights_name: str,
    sampler_path: str,
    registry_path: Path,
    metadata: Optional[dict[str, object]] = None,
) -> None:
    """Persist adapter name -> sampler path locally for reuse.

    Thread-safe: registry read-modify-write is serialized via _REGISTRY_LOCK
    so concurrent SFT workers don't clobber each other's entries.
    """
    with _REGISTRY_LOCK:
        registry_path.parent.mkdir(parents=True, exist_ok=True)
        if registry_path.exists():
            try:
                with registry_path.open("r", encoding="utf-8") as fh:
                    registry = json.load(fh)
            except Exception:
                registry = {}
        else:
            registry = {}
        entry: dict[str, object] = {"path": sampler_path}
        if metadata:
            entry.update(metadata)
        registry[weights_name] = entry
        with registry_path.open("w", encoding="utf-8") as fh:
            json.dump(registry, fh, indent=2, sort_keys=True)
        print(f"Recorded adapter mapping in {registry_path}: {weights_name} -> {sampler_path}")
