"""Backend-neutral training helpers shared by the Tinker and local-GPU backends.

These pieces carry NO tinker/torch dependency, so both
:mod:`dementor.training.tinker_backend` and :mod:`dementor.training.local_backend`
import them from here. ``tinker_backend`` re-exports every name below (plus the
``TinkerSFTOutcome = SFTOutcome`` back-compat alias) so existing import paths keep
resolving.
"""
from __future__ import annotations

import json
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import pandas as pd

from .data import (
    FinetuneExample,
    dataframe_to_finetune_examples,
    load_csv_dataset,
    sample_supervised_splits,
)


@dataclass(frozen=True)
class SFTDatasetConfig:
    """Configuration describing how to build supervised train/eval splits."""

    dataset_csv: Path | None = None
    train_csv: Path | None = None
    eval_csv: Path | None = None
    prompt_column: str = "prompt"
    completion_column: str = "model_response"
    dataset_size: int = 500
    train_size: int = 300
    eval_size: int = 200
    seed: int = 42


@dataclass(frozen=True)
class EvaluationConfig:
    """Configuration for sampling-based evaluation."""

    max_sample_tokens: int = 256
    stop_sequences: Optional[list[str]] = None


@dataclass(frozen=True)
class SFTOutcome:
    """Artifacts generated by an SFT run."""

    loss_history: list[float]
    eval_results: pd.DataFrame
    output_csv: Path
    sampler_path: Optional[str] = None


def prepare_sft_examples(config: SFTDatasetConfig) -> tuple[list[FinetuneExample], list[FinetuneExample]]:
    """Load CSV data and return train/eval splits as FinetuneExamples."""
    if config.train_csv or config.eval_csv:
        if config.train_csv is None:
            raise ValueError("train_csv must be provided when using explicit split files.")
        train_df = load_csv_dataset(
            path=config.train_csv,
            required_columns=[config.prompt_column, config.completion_column],
        )
        if config.eval_csv:
            eval_df = load_csv_dataset(
                path=config.eval_csv,
                required_columns=[config.prompt_column, config.completion_column],
            )
        else:
            eval_df = train_df.iloc[:0].copy()
    else:
        if config.dataset_csv is None:
            raise ValueError("dataset_csv must be provided when explicit split files are not used.")
        df = load_csv_dataset(
            path=config.dataset_csv,
            required_columns=[config.prompt_column, config.completion_column],
        )
        train_df, eval_df = sample_supervised_splits(
            df=df,
            dataset_size=config.dataset_size,
            train_size=config.train_size,
            eval_size=config.eval_size,
            seed=config.seed,
        )
    train_examples = dataframe_to_finetune_examples(train_df, config.prompt_column, config.completion_column)
    eval_examples = dataframe_to_finetune_examples(eval_df, config.prompt_column, config.completion_column)
    return train_examples, eval_examples


def format_example(example: FinetuneExample, template: str, index: int) -> str:
    """Render a prompt/completion template (prompt and completion formatting are identical)."""
    return template.format(prompt=example.prompt.strip(), completion=example.completion.strip(), index=index)


# ``format_prompt``/``format_completion`` had byte-identical bodies; keep both names as
# thin aliases of the single impl above (both are imported across the codebase).
format_prompt = format_example
format_completion = format_example


_REGISTRY_LOCK = threading.Lock()


def record_adapter_mapping(
    weights_name: str,
    sampler_path: str,
    registry_path: Path,
    metadata: Optional[dict[str, object]] = None,
) -> None:
    """Persist adapter name -> sampler path locally for reuse.

    Thread-safe: registry read-modify-write is serialized via _REGISTRY_LOCK
    so concurrent SFT workers don't clobber each other's entries.
    """
    import fcntl
    import os as _os
    import time as _time

    with _REGISTRY_LOCK:  # in-process guard
        registry_path.parent.mkdir(parents=True, exist_ok=True)
        lock_path = registry_path.with_suffix(registry_path.suffix + ".lock")
        with open(lock_path, "w", encoding="utf-8") as _lk:
            fcntl.flock(_lk.fileno(), fcntl.LOCK_EX)  # cross-PROCESS mutual exclusion
            registry: dict = {}
            if registry_path.exists() and registry_path.stat().st_size > 0:
                parsed = None
                for _ in range(5):
                    try:
                        with registry_path.open("r", encoding="utf-8") as fh:
                            parsed = json.load(fh)
                        break
                    except Exception:
                        _time.sleep(0.2)
                if parsed is None:
                    # A non-empty registry that will not parse means corruption, NOT "start fresh".
                    # Refuse to overwrite it with {} (the bug that truncated 1554 entries -> 16).
                    raise RuntimeError(
                        f"registry {registry_path} exists ({registry_path.stat().st_size} bytes) "
                        "but could not be parsed; refusing to overwrite")
                registry = parsed
            entry: dict[str, object] = {"path": sampler_path}
            if metadata:
                entry.update(metadata)
            registry[weights_name] = entry
            tmp = registry_path.with_suffix(registry_path.suffix + ".tmp")
            with tmp.open("w", encoding="utf-8") as fh:
                json.dump(registry, fh, indent=2, sort_keys=True)
            _os.replace(tmp, registry_path)  # atomic swap; readers never see a partial file
        print(f"Recorded adapter mapping in {registry_path}: {weights_name} -> {sampler_path}")
