_wandb:
    value:
        cli_version: 0.19.9
        code_path: code/disguise.py
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 53
                - 55
                - 95
                - 97
                - 105
            "2":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 53
                - 55
                - 95
                - 97
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.13
            "5": 0.19.9
            "6": 4.51.0
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
al_batch_size:
    value: 10
al_d_regular:
    value: 3
al_max_iterations:
    value: 5
al_num_examples:
    value: 5
al_p_threshold:
    value: 0.1
al_q_threshold:
    value: 0.1
al_relaxation_factor:
    value: 1.2
al_seed:
    value: null
disguise_as:
    value: gpt-4.1
example_selector:
    value: al
heuristics_only:
    value: false
judge_api_base:
    value: https://api.openai.com/v1
judge_api_key:
    value: null
judge_model:
    value: openai/gpt-4.1-mini
method:
    value: random_sampling
model:
    value: meta-llama/Meta-Llama-3-8B-Instruct
no_wandb:
    value: false
num_samples:
    value: 2
openai_api_base:
    value: null
openai_api_key:
    value: null
output_dir:
    value: /home/nazcol/dementor-sync/data/results/call_center/
prompts_file:
    value: null
run_name:
    value: meta-llama_Meta-Llama-3-8B-Instruct_disguised-gpt-4.1_responses-2
skip_evaluation:
    value: false
source_responses:
    value: /home/nazcol/dementor-sync/data/model-responses/call_center/meta-llama_Meta-Llama-3-8B-Instruct-500.csv
target_responses:
    value: /home/nazcol/dementor-sync/data/model-responses/call_center/gpt-4.1.csv
tensor_paralel_size:
    value: 2
